### ISSUE TITLE
Support WORKSPACE.bazel and BUILD.bazel files

### ISSUE THREAD

**Issue by kgreenek** [alexander-born/bazel.nvim#2]
Bazel supports the .bazel extension for these files. So instead of WORKSPACE, the file can be named WORKSPACE.bazel. And similarly, instead of BUILD, these files can be named BUILD.bazel.

This plugin seems to rely on the former names, and does not work when using the .bazel extension. This prevents it from being usable for me.

Love this work! Excited to be able to use it. I appreciate any support you're willing to give.

**Comment by alexander-born** [comment]
Hey, I just pushed a fix. Can you try if it works for you now?

**Comment by kgreenek** [comment]
It works! Thank you! This is a game changer for me :)
