### ISSUE TITLE
Feature request: Support jumping to macro definitions / rules in load statements

### ISSUE THREAD

**Issue by kgreenek** [alexander-born/bazel.nvim#3]
Right now it is only possible to jump to targets.

Example BUILD.bazel file:

```
load("@rules_python//python:defs.bzl", "py_library", "py_test")
```

When I run GoToBazelDefinition with the cursor on py_library or py_test, I see the following message:

```
Failed to find the definition
```

If I try to run GoToBazelDefinition with the cursor over "@rules_python//python:defs.bzl", I see the following exception:

```
E5108: Error executing lua: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):                                                                          
  File "<string>", line 1, in <module>
  File "/home/kgk/.local/share/nvim/site/pack/packer/start/bazel.nvim/plugin/bazel_vim.py", line 23, in find_definiti
on
    result = bazel.find_definition_at(
  File "/home/kgk/.local/share/nvim/site/pack/packer/start/bazel.nvim/plugin/bazel.py", line 190, in find_definition_
at
    return find_definition(node.s, fname, workspace_root)
  File "/home/kgk/.local/share/nvim/site/pack/packer/start/bazel.nvim/plugin/bazel.py", line 152, in find_definition 
    for lineno, name in collect_targets(parse_file_by_name(build_fname)):
  File "/home/kgk/.local/share/nvim/site/pack/packer/start/bazel.nvim/plugin/bazel.py", line 17, in parse_file_by_nam
e
    return parse_file(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/home/kgk/.cache/bazel/_bazel_kgk/ec654fdc5ba6a08f3050c551a6
e071c3/external/rules_python/python/BUILD.bazel'
stack traceback:
        [C]: at 0x5573543779b3
```

It would be extremely useful to be able to jump to the macro definition, or into the defs.bzl file.

**Comment by kgreenek** [comment]
I just realized this already works if I run GoToBazelDefinition with the cursor on the usage instead of in the load statement.

So for example, this works:

```bzl
py_binary(
    name = "foo",
    ...
)
```

If the cursor is on py_binary and I press `gd`, then it will jump into defs.bzl! It only fails when I try to do that in the load statement.

**Comment by alexander-born** [comment]
Yes, goto definition on the load statement line is not supported yet. Load statement resolution is supported though as you already mentioned. I'll add support for the load statement line if I have free time again.

**Comment by alexander-born** [comment]
Should work now! Thanks for using this plugin :)
![load_statment_resolution](https://user-images.githubusercontent.com/61082865/235901996-2d18bcfc-2c65-4274-8ba6-fdfc7ff07856.gif)

**Comment by kgreenek** [comment]
It works! This is amazing, thank you!
