### ISSUE TITLE
output_base does not respect vim.g.bazel_cmd

### ISSUE THREAD

**Issue by Witnessthis** [alexander-born/bazel.nvim#5]
I'm using vim.g.bazel_cmd to change the bazel cmd since we have our own bazel wrapper script as our entrypoint to bazel.

It seems howevcer that output_base in workspace.py does not respect this setting. Manually changing "bazel" to the path of my bazel entrypoint fixes the issue for me. But ideally we should probably rely on vim.g.bazel_vim option if it is set.

**Comment by alexander-born** [comment]
Hey, thanks for bringing up this issue. 
If you want to fix this I am happy to merge a PR. Otherwise I will take care of this. I am not sure, when I will come to it though.

**Comment by Witnessthis** [comment]
I have a patch for it, I just need to clear it due to company policies before I upstream it.

**Comment by alexander-born** [comment]
I wanted to safe you the troubles with your company policies and the fix was rather easy. Should respect the `g:bazel_cmd` now.

**Comment by Witnessthis** [comment]
That’s great, thank you :)
